<?php

return [

    'extra_labels' => [
        'tolshchina_materiala'              => 'Толщина материала',
        'gabarity'                          => 'Габариты',
        'toplivo'                           => 'Топливо',
        'kolichestvo_konteynerov'          => 'Количество контейнеров',
        'obshchaya_liniya_ognya'           => 'Общая линия огня',
        'vysota_vstraivayemaya'            => 'Высота встраиваемая',
        'shirina_vstraivayemaya'           => 'Ширина встраиваемая',
        'glubina_vstraivayemaya'           => 'Глубина встраиваемая',
        'maksimalnoe_vremya_goreniya'      => 'Максимальное время горения',
        'seriya_kaminov'                   => 'Серия каминов',
        'raskhod_biotopliva'              => 'Расход биотоплива',
        'material_tb'                      => 'Материал топливного блока',
        'tip_biokamina'                    => 'Тип биокамина',
        'tolshchina_ochaga'                => 'Толщина очага',
        'tolshchina_kryshki_toplivnogo_bloka' => 'Толщина крышки топливного блока',
        'seriya_toplivnogo_bloka'          => 'Серия топливного блока',
        'obshchiy_razmer_tb'               => 'Общий размер топливного блока',
        'obem_toplivnogo_bloka'            => 'Объём топливного блока',
        'obem_zalivaemogo_topliva'         => 'Объём заливаемого топлива',
        'klass_rashoda_biotopliva'         => 'Класс расхода биотоплива',
        'vid_ognya'                        => 'Вид огня',
        'tolshchina_stekla'                => 'Толщина стекла',
        'material_ochaga'                  => 'Материал очага',

        'kolichestvo_rezhimov_ognya'       => 'Количество режимов огня',
        'tip_upravleniya'                  => 'Тип управления',
        'sposob_upravleniya'               => 'Способ управления',
        'maksimalnaya_potrebljayemaya_moshchnost' => 'Макс. потребляемая мощность',
        'tip_gaza'                         => 'Тип газа',
        'nominalnoe_vkhodnoe_davlenie'     => 'Номинальное входное давление',
        'minimalnoe_vkhodnoe_davlenie'     => 'Минимальное входное давление',
        'maksimalnoe_vkhodnoe_davlenie'    => 'Максимальное входное давление',
        'avtomaticheskoe_upravlenie'       => 'Автоматическое управление',

        'tip_ustroystva'                   => 'Тип устройства',
        'shirina_dveri'                    => 'Ширина двери',
        'vysota_dveri'                     => 'Высота двери',
        'diametr_dymokhoda'                => 'Диаметр дымохода',
        'prisoyedinenie_dymokhoda'         => 'Присоединение дымохода',
        'forma_stekla_i_dverey'            => 'Форма стекла и дверей',
        'moshchnost'                       => 'Мощность',
        'maksimalnaya_dlinna_drov'         => 'Максимальная длина дров',
        'kpd'                              => 'КПД',
        'sposob_otkrytiya_dvertsy'         => 'Способ открытия дверцы',
        'nalichie_dymosbornika'            => 'Наличие дымосборника',
        'futerovka'                        => 'Футеровка',
        'nalichie_zolnika'                 => 'Наличие зольника',
        'teplooobmenik'                    => 'Теплообменник',
        'moshchnost_teplooobmenika'        => 'Мощность теплообменника',
        'tip_dverki'                       => 'Тип дверки',
        'podacha_vozdushka_izvne'          => 'Подача воздуха извне',
        'raspolozhenie_v_pomeshchenii'     => 'Расположение в помещении',
        'dizayn_i_ispolnenie'              => 'Дизайн и исполнение',
        'material_oblitcovki'              => 'Материал облицовки',
        'tip_nagrevanija'                  => 'Тип нагревания',
        'optsii_kaminov_i_pechey'          => 'Опции каминов и печей',
        'vysota_kaminokomplekta'           => 'Высота каминокомплекта',
        'nalichie_balki'                   => 'Наличие балки',
        'three_d'                          => '3D / трёхмерная футеровка',
        'vtorichnyy_dozhig'                => 'Вторичный дожиг',
        'sistema_chistogo_stekla'          => 'Система чистого стекла',
        'klass_energoemkosti'              => 'Класс энергоёмкости',
        'rezerv3'                          => 'Резерв 3',

        'tekhnologiya_plameni'             => 'Технология пламени',
        'tip_ochaga'                       => 'Тип очага',
        'obem'                             => 'Объём',
        'moshchnost_obogreva'              => 'Мощность обогрева',
        'pult_du'                          => 'Пульт ДУ',
        'otlichitelnye_osobennosti'        => 'Отличительные особенности',
        'optsii'                           => 'Опции',
        'tsvet_ochaga'                     => 'Цвет очага',
        'tsvet_dereva'                     => 'Цвет дерева',
        'tsvet_kamnya'                     => 'Цвет камня',
        'material_korpusa'                 => 'Материал корпуса',
        'rezerv'                           => 'Резерв',
        'diametr_dymokhoda_dymokhody'      => 'Диаметр дымохода (дымоходы)',
        'rezerv1'                          => 'Резерв 1',
    ],

];
